import { env } from "./env";

// Table IDs in the "Paying Clients & Billing" base.
export const TABLES = {
  clients: "tblZK7NcIJrkv4GPJ",
  deals: "tblEaxP5Nml7neANT",
  projects: "tblcAZMc0kF3drvsm",
  pulseSurveys: "tblY8jSdQoMN8vgGZ",
} as const;

export type AirtableRecord<F> = { id: string; createdTime: string; fields: F };

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${env.airtableApiUrl()}/v0/${env.airtableBaseId()}/${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${env.airtableToken()}`,
      "Content-Type": "application/json",
      ...init?.headers,
    },
    cache: "no-store",
  });
  if (!res.ok) {
    throw new Error(`Airtable ${init?.method ?? "GET"} ${path} failed: ${res.status} ${await res.text()}`);
  }
  return res.json() as Promise<T>;
}

export async function findOne<F>(table: string, formula: string): Promise<AirtableRecord<F> | null> {
  const params = new URLSearchParams({ filterByFormula: formula, maxRecords: "1" });
  const data = await request<{ records: AirtableRecord<F>[] }>(`${table}?${params}`);
  return data.records[0] ?? null;
}

export async function getRecord<F>(table: string, id: string): Promise<AirtableRecord<F>> {
  return request<AirtableRecord<F>>(`${table}/${id}`);
}

export async function updateRecord<F>(table: string, id: string, fields: Partial<F>): Promise<AirtableRecord<F>> {
  return request<AirtableRecord<F>>(`${table}/${id}`, {
    method: "PATCH",
    body: JSON.stringify({ fields, typecast: true }),
  });
}

// Tokens are generated by n8n (32+ url-safe chars). Validating the shape also
// makes them safe to interpolate into an Airtable formula.
export function isValidToken(token: string): boolean {
  return /^[A-Za-z0-9_-]{16,64}$/.test(token);
}
